In [21]:
import pandas as pd
import numpy as np
import cvxpy as cvx
import random
import time
from __future__ import print_function
from builtins import input

from sporco.admm import bpdn
### using the ADMM algorithm 
### we can also use the PGM algorithm 
from sporco import util
from sporco import plot
plot.config_notebook_plotting()

from scipy.linalg import hadamard

import matplotlib.pyplot as plt

from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import KFold

from scipy import stats
from matplotlib import pyplot
from scipy.stats import spearmanr

import warnings
warnings.filterwarnings("ignore")


import seaborn as sns

table = pd.read_pickle("A8.pkl")
iHiVred = pd.read_pickle("iHiV7.pkl")
iHiV = pd.read_pickle("iHiV8.pkl")
VHred = pd.read_pickle("VH7.pkl")
tableg = table.T

#iFT = pd.read_pickle("iFT4.pkl")

VH = pd.read_pickle("VH8.pkl")
tableg = table.T
B = pd.read_pickle("B8.pkl")

Bdf = pd.DataFrame(B)

species_ones = [] 
for i in range(8):
    species = i
    species_ones.append(list(tableg[tableg[species]==1].index))
    
    
species_zeros = []
for i in range(8):
    species = i
    species_zeros.append(list(tableg[tableg[species]==0].index))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       


#### get all data -- design matrix, steady state abundances, and list of wells present

sst = pd.read_pickle("Friedman-data-sst-rel.pkl")
#sst = pd.read_pickle("will-ludd-log10-properdata.pkl")
sstv3 = sst.copy()

laml = [1e-20,1e-10,1e-5,.01,.02,.03,.04,.05,.06,.0650,.0675,.07,0.08,0.1,0.13,0.15,0.18,0.2,0.5,1.0,2.0,3.0,5.0,10.0,20.0]
from sklearn.metrics import r2_score

g = np.array([[1, 0], [-1, 1]])

for i in range(6):
    g = np.block([[g, np.zeros(g.shape)], [-g, g]])

G = g
X = np.linalg.inv(G)

import matplotlib.font_manager as fm
 
gs_font = fm.FontProperties(fname='gillsans.ttf', size=15, weight='bold')
light_grey=(0.5,0.5,0.5)



import matplotlib.font_manager as fm


fontSize=12
fontSizeSmall=10
labelSize=8


machine_precision=1e-6



SMALL_SIZE = 10
MEDIUM_SIZE = 12
BIGGER_SIZE = 14

BIGGEST_SIZE = 18
# plt.rc('font', size=SMALL_SIZE, family='sans-serif', serif='Arial')          # controls default text sizes
plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=BIGGER_SIZE, titleweight='bold')     # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE, labelweight='bold')    # fontsize of the x and y labels
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('legend', fontsize=SMALL_SIZE)    # legend fontsize
plt.rc('figure', titlesize=BIGGER_SIZE)  # fontsize of the figure title
plt.rc('text')



from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_percentage_error as mape

In [22]:
list_present  = pd.read_pickle("list-present-friedman.pkl")
sst_rel = pd.read_pickle("Friedman-data-sst-relv2.pkl")

In [23]:
sp_list_provided = ["Ea","Pa","Pch","Pci","Pf","Pp","Pv","Sm"] 
sst_rel2 = sst_rel.rename(columns={"Sm":0,"Pv":1,"Pp":2,"Pf":3,"Pci":4,"Pch":5,"Pa":6,"Ea":7})
sstv3 = sst_rel2[[0,1,2,3,4,5,6,7,"well index"]]

In [24]:
sstv4 = sstv3.fillna(0)

In [25]:
sstv4.head(3)

     0    1    2    3    4    5    6    7  well index
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0           0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0           1
2  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0           2

In [26]:
n = 2**7
random_state = 78
cv_splitsl = [3,5,7]

In [27]:
to_be_removed = {73,164,193}
list_presentv2 = [item for item in list_present if item not in to_be_removed ]

In [28]:
opt = bpdn.BPDN.Options({'Verbose': False, 'MaxMainIter': 500,
                         'RelStopTol': 1e-8, 'AutoRho': {'RsdlTarget': 1.0}})

In [29]:
errdf = pd.read_pickle("CS-rel-WH.pkl")
errlindf = pd.read_pickle("CS-rel-sigma.pkl")

In [33]:
crossval = [] 
for m in cv_splitsl:
    samp = errdf[errdf[5]==m]
    for speciesc in range(8):
        bspecies = Bdf.T[species_ones[speciesc]].T
        bspecies["index all"] = bspecies.index
        bspecies.index = np.arange(0,2**7,1)
        abunvec = pd.DataFrame(sstv4[speciesc].values).T[species_ones[speciesc]].T
        abunvec.index = np.arange(0,2**7,1)
        listl = list(abunvec.T[list(bspecies[bspecies["index all"].isin(list_presentv2)].index)].T.index)
        sp1 = samp[samp[1]==speciesc]
        for rhola in laml:
            rho1 = sp1[sp1[0]==rhola]
            r2 = [] 
            yallbest  = []
            yallact  = [] 
            for iterii in range(m):
                idx = rho1[3].iloc[iterii]
                yact = abunvec.T[idx].T[0].values.astype(float)
                ybest = rho1[2].iloc[iterii]
                ybestdf1 = pd.DataFrame(ybest)
                ybestdf1[ybestdf1[0]<1e-10]=0
                yallbest.append(ybestdf1[0].values)
                yallact.append(yact)
                #slope, intercept,r_value, p_value, std_err = stats.linregress(yact,ybestdf1[0].values)
                rval = r2_score(yact,ybestdf1[0].values)
                gop = 1/(2-rval)
                mape1 = mape(yact,ybestdf1[0].values)
                r2.append([gop,rval,mape1,slope,intercept,r_value**2])
            r2df = pd.DataFrame(r2)
            if m == 2:
                ybestagg = [*yallbest[0],*yallbest[1]]
                yactagg = [*yallact[0],*yallact[1]]
            if m == 3:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2]]
            if m == 5:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4]]
            if m == 7:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4],*yallbest[5],*yallbest[6]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4],*yallact[5],*yallact[6]]
            if m == 9:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4],*yallbest[5],*yallbest[6],*yallbest[7],*yallbest[8]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4],*yallact[5],*yallact[6],*yallact[7],*yallact[8]]
            slope, intercept,r_value, p_value, std_err = stats.linregress(yactagg,ybestagg)
            rval2 = r2_score(yactagg,ybestagg)
            gop2 = 1/(2-rval2)
            mean1 = r2df.mean().values[0]
            mean2 = r2df.mean().values[1]
            mean3 = r2df.mean().values[2]
            mean4 = r2df.mean().values[3]
            mean5 = r2df.mean().values[4]
            mean6 = r2df.mean().values[5]
            mape2 = mape(yactagg,ybestagg)
            crossval.append([m,speciesc,rhola,gop2,rval2,mape2,slope,intercept,r_value**2,"break",mean1,mean2,mean3,mean4,mean5,mean6,yactagg,ybestagg])

In [34]:
crossdf = pd.DataFrame(crossval,columns=["k-fold","sp","lambda","nnseagg","r2agg","mapeagg","slagg","intagg","rlinagg","means on right","nnseavg","r2avg","mapeavg","slavg","intavg","rlinavg","testact","testpred"])

In [35]:
crossdf.head(2)

,k-fold,sp,lambda,nnseagg,r2agg,mapeagg,slagg,intagg,rlinagg,means on right,nnseavg,r2avg,mapeavg,slavg,intavg,rlinavg,testact,testpred
0,3,0,1.000000e-20,1.151704e-247,-8.682784e+246,4.729411e+135,-2.936103e+122,1.994922e+122,0.010231,break,1.978512e-224,-1.713771e+248,4.598038e+135,1.952795e+118,8.124858e+117,0.337311,"[1.0, 0.0037593984962406082, 0.476615768750865...","[1.3049581304575596e+111, 1.6104833249766265e+..."
1,3,0,1.000000e-10,5.587178e-01,2.101878e-01,2.438732e+12,3.915692e-01,6.889929e-02,0.288431,break,4.758507e-01,-2.525784e-01,2.370989e+12,-2.936103e+122,1.994922e+122,0.010231,"[1.0, 0.0037593984962406082, 0.476615768750865...","[0.4759271672557144, 0.011193626014796648, 0.3..."

In [36]:
crossvalin = [] 
for m in cv_splitsl:
    samp = errlindf[errlindf[5]==m]
    for speciesc in range(8):
        bspecies = Bdf.T[species_ones[speciesc]].T
        bspecies["index all"] = bspecies.index
        bspecies.index = np.arange(0,2**7,1)
        abunvec = pd.DataFrame(sstv4[speciesc].values).T[species_ones[speciesc]].T
        abunvec.index = np.arange(0,2**7,1)
        listl = list(abunvec.T[list(bspecies[bspecies["index all"].isin(list_presentv2)].index)].T.index)
        sp1 = samp[samp[1]==speciesc]
        for rhola in laml:
            rho1 = sp1[sp1[0]==rhola]
            r2 = [] 
            yallbest  = []
            yallact  = [] 
            for iterii in range(m):
                idx = rho1[3].iloc[iterii]
                yact = abunvec.T[idx].T[0].values.astype(float)
                ybest = rho1[2].iloc[iterii]
                ybestdf1 = pd.DataFrame(ybest)
                ybestdf1[ybestdf1[0]<1e-10]=0
                yallbest.append(ybestdf1[0].values)
                yallact.append(yact)
                #slope, intercept,r_value, p_value, std_err = stats.linregress(yact,ybestdf1[0].values)
                rval = r2_score(yact,ybestdf1[0].values)
                gop = 1/(2-rval)
                mape1 = mape(yact,ybestdf1[0].values)
                r2.append([gop,rval,mape1,slope,intercept,r_value**2])
            r2df = pd.DataFrame(r2)
            if m == 2:
                ybestagg = [*yallbest[0],*yallbest[1]]
                yactagg = [*yallact[0],*yallact[1]]
            if m == 3:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2]]
            if m == 5:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4]]
            if m == 7:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4],*yallbest[5],*yallbest[6]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4],*yallact[5],*yallact[6]]
            if m == 9:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4],*yallbest[5],*yallbest[6],*yallbest[7],*yallbest[8]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4],*yallact[5],*yallact[6],*yallact[7],*yallact[8]]
            slope, intercept,r_value, p_value, std_err = stats.linregress(yactagg,ybestagg)
            rval2 = r2_score(yactagg,ybestagg)
            gop2 = 1/(2-rval2)
            mean1 = r2df.mean().values[0]
            mean2 = r2df.mean().values[1]
            mean3 = r2df.mean().values[2]
            mean4 = r2df.mean().values[3]
            mean5 = r2df.mean().values[4]
            mean6 = r2df.mean().values[5]
            mape2 = mape(yactagg,ybestagg)
            crossvalin.append([m,speciesc,rhola,gop2,rval2,mape2,slope,intercept,r_value**2,"break",mean1,mean2,mean3,mean4,mean5,mean6,yactagg,ybestagg])

In [37]:
crosslindf = pd.DataFrame(crossvalin,columns=["k-fold","sp","lambda","nnseagg","r2agg","mapeagg","slagg","intagg","rlinagg","means on right","nnseavg","r2avg","mapeavg","slavg","intavg","rlinavg","testact","testpred"])

In [38]:
crosslindf.head(2)

,k-fold,sp,lambda,nnseagg,r2agg,mapeagg,slagg,intagg,rlinagg,means on right,nnseavg,r2avg,mapeavg,slavg,intavg,rlinavg,testact,testpred
0,3,0,1.000000e-20,2.186276e-232,-4.573987e+231,3.152934e+129,1.149486e+115,5.287693e+114,0.034765,break,0.094892,-5.602819e+231,3.065353e+129,0.000000e+00,0.000000e+00,0.000000,"[1.0, 0.0037593984962406082, 0.476615768750865...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,3,0,1.000000e-10,3.328792e-01,-1.004093e+00,2.845692e+14,-7.043482e-02,2.881212e-01,0.006193,break,0.242837,-1.331766e+01,2.956625e+14,1.149486e+115,5.287693e+114,0.034765,"[1.0, 0.0037593984962406082, 0.476615768750865...","[0.32184386867688025, 0.318066640422457, 0.321..."

In [39]:
pd.to_pickle(crossdf,"WH-REL-analysis.pkl")
pd.to_pickle(crosslindf,"sigma-REL-analysis.pkl")