In [4]:
import pandas as pd
import numpy as np

import random

from scipy import stats
from matplotlib import pyplot
from scipy.stats import spearmanr

import warnings
warnings.filterwarnings("ignore")


table = pd.read_pickle("~/compressed_sensingv1/realdatasets/misc/will-luddington-v4/A5.pkl")

tableg = table.T

B = pd.read_pickle("~/compressed_sensingv1/realdatasets/misc/will-luddington-v4/B5.pkl")

Bdf = pd.DataFrame(B)

species_ones = [] 
for i in range(5):
    species = i
    species_ones.append(list(tableg[tableg[species]==1].index))
    
    
species_zeros = []
for i in range(5):
    species = i
    species_zeros.append(list(tableg[tableg[species]==0].index))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       


#sst = pd.read_pickle("~/compressed_sensingv1/realdatasets/misc/will-luddington-v5/Gould-etal-5species-relative-abundance-Oct22.pkl")
sst = pd.read_pickle("~/compressed_sensingv1/realdatasets/will-luddington-v7/Gould-etal-5species-relative-abundance-Feb23median.pkl")
sstv3 = sst.copy()

VHred = pd.read_pickle("~/compressed_sensingv1/realdatasets/misc/will-luddington-v4/VH4.pkl")
betasact = []
for species in range(5):
    abunvec = pd.DataFrame(sstv3[species][species_ones[species]].values)
    betasact.append([species,np.dot(VHred,abunvec).ravel()])
betac = pd.DataFrame(betasact)



laml = [1e-100,1e-30,5e-30,1e-25,1e-20,5e-20,500e-20,1e-11,1e-10,1e-5,.01,.05,.06,.0650,.0675,.07,0.08,0.1,0.13,0.15,0.18,0.2,0.5,1.0,2.0]
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_percentage_error as mape

In [5]:
#### analysis part begins 
errdf = pd.read_pickle("rel_CS_WH.pkl")
errlindf = pd.read_pickle("rel_l1_sigma.pkl")

In [6]:
sp_list_provided = ['LP', 'LB', 'AP', 'AT', 'AO']

n = 2**5
random_state = None
cv_splitsl = [3]

In [7]:
crossval = [] 
for m in cv_splitsl:
    samp = errdf[errdf[5]==m]
    for species in range(5):
        abunvec = pd.DataFrame(sstv3[species][species_ones[species]].values)
        sp1 = samp[samp[1]==species]
        for rhola in laml:
            rho1 = sp1[sp1[0]==rhola]
            r2 = [] 
            yallbest  = []
            yallact  = [] 
            for iterii in range(m):
                idx = rho1[3].iloc[iterii]
                yact = abunvec.T[idx].T[0].values.astype(float)
                ybest = rho1[2].iloc[iterii]
                ybestdf1 = pd.DataFrame(ybest)
                ybestdf1[ybestdf1[0]<1e-10]=0
                slope, intercept,r_value, p_value, std_err = stats.linregress(yact,ybestdf1[0].values)
                yallbest.append(ybestdf1[0].values)
                yallact.append(yact)
                rval = r2_score(yact,ybestdf1[0].values)
                gop = 1/(2-rval)
                mape1 = mape(yact,ybestdf1[0].values)
                r2.append([gop,rval,mape1,slope,intercept,r_value**2])
                
            r2df = pd.DataFrame(r2)
            if m == 2:
                ybestagg = [*yallbest[0],*yallbest[1]]
                yactagg = [*yallact[0],*yallact[1]]
            if m == 3:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2]]
            if m == 5:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4]]
            if m == 7:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4],*yallbest[5],*yallbest[6]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4],*yallact[5],*yallact[6]]
            #print(r2_score(yactagg,ybestagg))
            #print(yactagg)
            slope, intercept,r_value, p_value, std_err = stats.linregress(yactagg,ybestagg)
            rval2 = r2_score(yactagg,ybestagg)
            gop2 = 1/(2-rval2)
            mean1 = r2df.mean().values[0]
            mean2 = r2df.mean().values[1]
            mean3 = r2df.mean().values[2]
            mean4 = r2df.mean().values[3]
            mean5 = r2df.mean().values[4]
            mean6 = r2df.mean().values[5]
            mape2 = mape(yactagg,ybestagg)
            crossval.append([m,species,rhola,gop2,rval2,mape2,slope,intercept,r_value**2,"break",mean1,mean2,mean3,mean4,mean5,mean6,yactagg,ybestagg])

In [8]:
crossdf = pd.DataFrame(crossval,columns=["k-fold","sp","lambda","nnseagg","r2agg","mapeagg","slagg","intagg","rlinagg","means on right","nnseavg","r2avg","mapeavg","slavg","intavg","rlinavg","testact","testpred"])

In [9]:
crossdf.head(5)

,k-fold,sp,lambda,nnseagg,r2agg,mapeagg,slagg,intagg,rlinagg,means on right,nnseavg,r2avg,mapeavg,slavg,intavg,rlinavg,testact,testpred
0,3,0,1.000000e-100,0.365607,-0.735175,2.794842e-01,2.680784e-01,3.218454e-01,0.064047,break,0.325014,-1.199594,2.825560e-01,5.272937e-01,1.887043e-01,0.378354,"[0.5189275604564749, 0.6293102879572517, 0.394...","[0.815500367991984, 0.30224111607705534, 0.342..."
1,3,0,1.000000e-30,0.365607,-0.735175,2.794842e-01,2.680784e-01,3.218454e-01,0.064047,break,0.325014,-1.199594,2.825560e-01,5.272937e-01,1.887043e-01,0.378354,"[0.5189275604564749, 0.6293102879572517, 0.394...","[0.815500367991984, 0.30224111607705534, 0.342..."
2,3,0,5.000000e-30,0.365607,-0.735175,2.794842e-01,2.680784e-01,3.218454e-01,0.064047,break,0.325014,-1.199594,2.825560e-01,5.272937e-01,1.887043e-01,0.378354,"[0.5189275604564749, 0.6293102879572517, 0.394...","[0.815500367991984, 0.30224111607705534, 0.342..."
3,3,0,1.000000e-25,0.365607,-0.735175,2.794842e-01,2.680784e-01,3.218454e-01,0.064047,break,0.325014,-1.199594,2.825560e-01,5.272937e-01,1.887043e-01,0.378354,"[0.5189275604564749, 0.6293102879572517, 0.394...","[0.815500367991984, 0.30224111607705534, 0.342..."
4,3,0,1.000000e-20,0.000000,-inf,3.794996e+155,5.601001e+155,-8.274094e+154,0.000000,break,0.208770,-inf,4.047996e+155,-1.040484e+155,2.862537e+155,0.139735,"[0.5189275604564749, 0.6293102879572517, 0.394...","[0.815500367991984, 0.30224111607705534, 0.342..."

In [10]:
crossvalin = [] 
for m in cv_splitsl:
    samp = errlindf[errlindf[5]==m]
    for species in range(5):
        abunvec = pd.DataFrame(sstv3[species][species_ones[species]].values)
        sp1 = samp[samp[1]==species]
        for rhola in laml:
            rho1 = sp1[sp1[0]==rhola]
            r2 = [] 
            yallbest  = []
            yallact  = [] 
            for iterii in range(m):
                idx = rho1[3].iloc[iterii]
                yact = abunvec.T[idx].T[0].values.astype(float)
                ybest = rho1[2].iloc[iterii]
                ybestdf1 = pd.DataFrame(ybest)
                ybestdf1[ybestdf1[0]<1e-10]=0
                slope, intercept,r_value, p_value, std_err = stats.linregress(yact,ybestdf1[0].values)
                yallbest.append(ybestdf1[0].values)
                yallact.append(yact)
                rval = r2_score(yact,ybestdf1[0].values)
                gop = 1/(2-rval)
                mape1 = mape(yact,ybestdf1[0].values)
                r2.append([gop,rval,mape1,slope,intercept,r_value**2])
                
            r2df = pd.DataFrame(r2)
            if m == 2:
                ybestagg = [*yallbest[0],*yallbest[1]]
                yactagg = [*yallact[0],*yallact[1]]
            if m == 3:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2]]
            if m == 5:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4]]
            if m == 7:
                ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4],*yallbest[5],*yallbest[6]]
                yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4],*yallact[5],*yallact[6]]
            #print(r2_score(yactagg,ybestagg))
            #print(yactagg)
            slope, intercept,r_value, p_value, std_err = stats.linregress(yactagg,ybestagg)
            rval2 = r2_score(yactagg,ybestagg)
            gop2 = 1/(2-rval2)
            mean1 = r2df.mean().values[0]
            mean2 = r2df.mean().values[1]
            mean3 = r2df.mean().values[2]
            mean4 = r2df.mean().values[3]
            mean5 = r2df.mean().values[4]
            mean6 = r2df.mean().values[5]
            mape2 = mape(yactagg,ybestagg)
            crossvalin.append([m,species,rhola,gop2,rval2,mape2,slope,intercept,r_value**2,"break",mean1,mean2,mean3,mean4,mean5,mean6,yactagg,ybestagg])

In [11]:
crosslindf = pd.DataFrame(crossvalin,columns=["k-fold","sp","lambda","nnseagg","r2agg","mapeagg","slagg","intagg","rlinagg","means on right","nnseavg","r2avg","mapeavg","slavg","intavg","rlinavg","testact","testpred"])

In [12]:
crosslindf.head(2)

,k-fold,sp,lambda,nnseagg,r2agg,mapeagg,slagg,intagg,rlinagg,means on right,nnseavg,r2avg,mapeavg,slavg,intavg,rlinavg,testact,testpred
0,3,0,1.000000e-100,0.25212,-1.966366,0.363193,0.43108,0.236787,0.069363,break,0.229578,-3.786945,0.355471,0.780779,0.063781,0.393793,"[0.5189275604564749, 0.6293102879572517, 0.394...","[0.983357968816376, 0.12009247615457264, 0.059..."
1,3,0,1.000000e-30,0.25212,-1.966366,0.363193,0.43108,0.236787,0.069363,break,0.229578,-3.786945,0.355471,0.780779,0.063781,0.393793,"[0.5189275604564749, 0.6293102879572517, 0.394...","[0.983357968816376, 0.12009247615457264, 0.059..."

In [13]:
pd.to_pickle(crossdf,"WH-REL-analysis.pkl")
pd.to_pickle(crosslindf,"sigma-REL-analysis.pkl")