In [81]:
import pandas as pd
import numpy as np
import cvxpy as cvx
import random
import time

import time 
from scipy import stats
from matplotlib import pyplot

import warnings
warnings.filterwarnings("ignore")

from sklearn.metrics import mean_absolute_percentage_error as mape



import matplotlib.font_manager as fm


fontSize=12
fontSizeSmall=10
labelSize=8


machine_precision=1e-6



SMALL_SIZE = 10
MEDIUM_SIZE = 12
BIGGER_SIZE = 14

BIGGEST_SIZE = 18
# plt.rc('font', size=SMALL_SIZE, family='sans-serif', serif='Arial')          # controls default text sizes
plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=BIGGER_SIZE, titleweight='bold')     # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE, labelweight='bold')    # fontsize of the x and y labels
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('legend', fontsize=SMALL_SIZE)    # legend fontsize
plt.rc('figure', titlesize=BIGGER_SIZE)  # fontsize of the figure title
plt.rc('text')

In [82]:
import matplotlib as mpl
from matplotlib import pyplot
import matplotlib.pyplot as plt
mpl.rcParams['font.family'] = 'sans-serif'
def set_violin_color(vp,color,mediancolor):
    plt.setp(vp['bodies'], facecolor=color, edgecolor="white",alpha=0.7)
    plt.setp(vp['cbars'], color = color)
    plt.setp(vp['cmins'], color = "black")
    plt.setp(vp['cmaxes'], color = "black")
    plt.setp(vp['cmeans'], color = "black")
    plt.setp(vp['cmedians'],color = mediancolor)

def make_violin_plot(dataframe,col0,mediancolor,legendlabel,diff):
    stepepi_master0 = dataframe
    bp0 = plt.violinplot(stepepi_master0, positions=np.array(range(len(stepepi_master0)))*3.0+diff,showmeans = True,showmedians=True)
    positions=np.array(range(len(stepepi_master0)))
    set_violin_color(bp0,col0,mediancolor)
    plt.plot([], c=col0, label=legendlabel)
    plt.legend(loc='upper left') 
    return positions

import seaborn as sns
colorlist1 = sns.color_palette("bright").as_hex()
sns.color_palette("bright")

from sklearn.metrics import r2_score

pa_redv1 = pd.read_pickle("~/compressed_sensingv1/realdatasets/misc/ophelli-ryan/eff-16-list1-red-pa.pkl")

##### compile the well numbers for each species for its presence 

species_ones = []
for i in range(16):
    species_ones.append(pa_redv1[pa_redv1[i]==1.0]["well number"].values)

ones_len = [] 
for ii in range(len(species_ones)):
    ones_len.append(len(species_ones[ii]))

In [83]:
steadystate = pd.read_pickle("~/compressed_sensingv1/realdatasets/misc/ophelli-ryan/eff-16-list1-red-sst-REL.pkl")
sst = steadystate.T

In [84]:
cv_splitsl = [3,5,7] 
max_depthl = [2,5,10,15,20]
ntrees = [100,200,300,400,500,1000]
max_featuresl = ["auto","sqrt","log2"]

In [120]:
rdf = pd.read_pickle("~/compressed_sensingv1/realdatasets/BENCHMARKING/RANDOM FOREST/OV-25sp-REL/RF-16sp-OV-REL.pkl")
rdf

,species,max_depth,n_trees,Xtrain,Xtest,ypred,k-fold,max_features
0,0,2,100,"[49412, 32900, 32896, 32788, 32800, 45062, 327...","[45188, 36996, 41093, 36870, 33028, 32769, 57349]","[0.7111890046732574, 0.32541637529120016, 0.20...",3,auto
1,0,2,100,"[45188, 36996, 41093, 36870, 33028, 32769, 573...","[49412, 32900, 32896, 32788, 32800, 45062, 32768]","[0.5491621954636399, 0.4020051518873972, 0.272...",3,auto
2,0,2,100,"[45188, 36996, 41093, 36870, 33028, 32769, 573...","[37024, 40965, 36994, 32770, 36998, 32772, 40967]","[0.7128196932822791, 0.16979295910840286, 0.12...",3,auto
3,0,2,100,"[49412, 32900, 32896, 32788, 32800, 45062, 327...","[45188, 36996, 41093, 36870, 33028, 32769, 57349]","[0.48128462315190423, 0.2801276022917617, 0.19...",3,sqrt
4,0,2,100,"[45188, 36996, 41093, 36870, 33028, 32769, 573...","[49412, 32900, 32896, 32788, 32800, 45062, 32768]","[0.45281509554486293, 0.31422944469805936, 0.2...",3,sqrt
...,...,...,...,...,...,...,...,...
21595,15,20,1000,"[3075, 173, 549, 4229, 2049, 3, 547, 161, 8355...","[32769, 157, 165, 1025, 1537, 2089, 151, 4231,...","[0.8237260146695802, 0.7839245938351878, 0.745...",7,log2
21596,15,20,1000,"[3075, 173, 549, 4229, 2049, 3, 547, 161, 8355...","[16385, 7, 2053, 35, 211, 25121, 31, 1187, 212...","[0.762808442853723, 0.7761940702799053, 0.6790...",7,log2
21597,15,20,1000,"[3075, 173, 549, 4229, 2049, 3, 547, 161, 8355...","[33, 4103, 8357, 133, 37, 24579, 2177, 25217, ...","[0.7944587757542755, 0.7988423966742297, 0.266...",7,log2
21598,15,20,1000,"[3075, 173, 549, 4229, 2049, 3, 547, 161, 8355...","[641, 289, 5, 3139, 417, 8739, 4097, 513, 4096...","[0.823100814951854, 0.6165041601094915, 0.3686...",7,log2
21599,15,20,1000,"[3075, 173, 549, 4229, 2049, 3, 547, 161, 8355...","[41093, 129, 141, 16929, 40965, 2257, 2465, 25...","[0.8785453027359041, 0.7692838972350321, 0.765...",7,log2

In [117]:
crossval = [] 
errdf = rdf 
for m in cv_splitsl:
    samp = errdf[errdf["k-fold"]==m]
    for speciesc in range(16):
        species = speciesc
        sp1 = samp[samp["species"]==speciesc]
        for md in max_depthl:
            rho1 = sp1[sp1["max_depth"]==md]
            for nest in ntrees: 
                ntre = rho1[rho1["n_trees"]==nest]
                for mfeats in max_featuresl:
                    mdf = ntre[ntre["max_features"]==mfeats]
                    #print(mdf["ypred"].iloc[0].shape)
                    r2 = [] 
                    mape2 = [] 
                    yallbest  = []
                    yallact  = [] 
                    for iterii in range(m):
                        idx = mdf["Xtest"].iloc[iterii]
                        #idx.sort()
                        yact = sst[idx].T[species].values
                        ybest = mdf["ypred"].iloc[iterii]
                        ybestdf1 = pd.DataFrame(ybest)
                        ybestdf1[ybestdf1[0]<1e-10]=0
                        slope, intercept,r_value, p_value, std_err = stats.linregress(yact,ybestdf1[0].values)
                        rval = r2_score(yact,ybestdf1[0].values)
                        gop = 1/(2-rval)
                        r2.append([gop,r2_score(yact,ybestdf1[0].values)])
                        mape2.append(mape(yact,ybestdf1[0].values))
                        yallbest.append(ybestdf1[0].values)
                        yallact.append(yact)
                        slope, intercept,r_value, p_value, std_err = stats.linregress(yact,ybestdf1[0].values)
                        rval = r2_score(yact,ybestdf1[0].values)
                        gop = 1/(2-rval)
                        mape1 = mape(yact,ybestdf1[0].values)
                        r2.append([gop,rval,mape1,slope,intercept,r_value**2])
                    r2df = pd.DataFrame(r2)
                    if m == 2:
                        ybestagg = [*yallbest[0],*yallbest[1]]
                        yactagg = [*yallact[0],*yallact[1]]
                    if m == 3:
                        ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2]]
                        yactagg = [*yallact[0],*yallact[1],*yallact[2]]
                    if m == 5:
                        ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4]]
                        yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4]]
                    if m == 6:
                        ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4],*yallbest[5]]
                        yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4],*yallact[5]]
                    if m == 7:
                        ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4],*yallbest[5],*yallbest[6]]
                        yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4],*yallact[5],*yallact[6]]
                    if m == 9:
                        ybestagg = [*yallbest[0],*yallbest[1],*yallbest[2],*yallbest[3],*yallbest[4],*yallbest[5],*yallbest[6],*yallbest[7],*yallbest[8]]
                        yactagg = [*yallact[0],*yallact[1],*yallact[2],*yallact[3],*yallact[4],*yallact[5],*yallact[6],*yallact[7],*yallact[8]]
                    slope, intercept,r_value, p_value, std_err = stats.linregress(yactagg,ybestagg)
                    rval2 = r2_score(yactagg,ybestagg)
                    gop2 = 1/(2-rval2)
                    mean1 = r2df.mean().values[0]
                    mean2 = r2df.mean().values[1]
                    mean3 = r2df.mean().values[2]
                    mean4 = r2df.mean().values[3]
                    mean5 = r2df.mean().values[4]
                    mean6 = r2df.mean().values[5]
                    mape2 = mape(yactagg,ybestagg)
                    crossval.append([m,species,md,nest,mfeats,gop2,rval2,mape2,slope,intercept,r_value**2,"break",mean1,mean2,mean3,mean4,mean5,mean6,yactagg,ybestagg])

In [118]:
crossdf = pd.DataFrame(crossval,columns=["k-fold","sp","max_depth","trees","features","nnseagg","r2agg","mapeagg","slagg","intagg","rlinagg","means on right","nnseavg","r2avg","mapeavg","slavg","intavg","rlinavg","testact","testpred"])

In [119]:
crossdf.head(2)

,k-fold,sp,max_depth,trees,features,nnseagg,r2agg,mapeagg,slagg,intagg,rlinagg,means on right,nnseavg,r2avg,mapeavg,slavg,intavg,rlinavg,testact,testpred
0,3,0,2,100,auto,0.471571,-0.120569,2.342606,0.157424,0.315483,0.064637,break,0.356912,-1.522468,2.342606,0.634797,0.270085,0.325192,"[0.3391491238628783, 0.16302582467502283, 0.07...","[0.7111890046732574, 0.32541637529120016, 0.20..."
1,3,0,2,100,sqrt,0.522023,0.084377,2.012423,0.091243,0.282424,0.088766,break,0.405142,-1.043594,2.012423,0.291128,0.261472,0.274752,"[0.3391491238628783, 0.16302582467502283, 0.07...","[0.48128462315190423, 0.2801276022917617, 0.19..."

In [121]:
pd.to_pickle(crossdf,"~/compressed_sensingv1/realdatasets/BENCHMARKING/RANDOM FOREST/OV-25sp-REL/RF-REL-analysis.pkl")
#pd.to_pickle(crosslindf,"sigma-REL-analysis.pkl")

In [122]:
yactagg

[0.8813238924609864,
 0.45975443207759403,
 0.32674690474605605,
 0.47662725911197723,
 0.47551323887311325,
 0.8849303926284838,
 0.49459899722456646,
 0.3777649188957123,
 0.23926157484685195,
 0.37018252096147486,
 0.25622173369741286,
 0.20406481346385108,
 0.9973632253247118,
 0.7447127591041816,
 0.7227740418870495,
 0.9657109732732453,
 0.44475043202614783,
 0.7856644923779901,
 0.9946973187201925,
 0.9831101722446597,
 0.2758579459559808,
 0.20453806541965613,
 0.2540309047064505,
 0.17894035998043095,
 0.3922632765337898,
 0.9846419329659406,
 0.8074079275310274,
 0.4791320076623877,
 0.4333526281476361,
 0.980448313701916,
 0.3847617360013141,
 0.9552993276479746,
 0.769473109238045,
 0.3542511020202408,
 0.3199534086574731,
 0.6598284652248334,
 0.8720075226921493,
 0.7273188306661209,
 0.4806908891643878,
 0.9186505074776095,
 0.4104049295341782,
 0.6113462362998038,
 0.3518096180574055,
 0.3928349562835378,
 0.41943282434995965,
 0.25359538137519777,
 0.20186434475924053,
 0.4471527992275456,
 0.4642625128557297,
 0.26693612600159033,
 0.9681962245477858,
 0.6226862672891459,
 0.5335107178166594,
 0.6767858134179564,
 0.39123126850522993,
 0.25656889217682954,
 0.29018787470355323,
 0.2437419434797945,
 0.7603911616295984,
 0.9958952126972032,
 0.4362986734124511,
 0.4137169121256364,
 0.3997592413195021,
 0.7775499476519068,
 0.993428677570618,
 0.37862102785034685,
 0.333476507339399,
 0.2060813988340682,
 0.30915944296739417,
 0.767183023378863,
 0.9895850279590674,
 0.7316906206977127,
 0.8145898790741377,
 0.5597400875215489,
 0.3559714110316839,
 0.23980752134785166,
 0.2869463528723871,
 0.22330002636446,
 0.3680693414765509,
 0.32678744927022685]