In [1]:
import pandas as pd
import numpy as np

import random

from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import KFold

from scipy import stats
from scipy.stats import spearmanr

import warnings
warnings.filterwarnings("ignore")



table = pd.read_pickle("~/compressed_sensingv1/realdatasets/misc/starch-sanchez-v3/matrices/A6.pkl")

tableg = table.T

B = pd.read_pickle("~/compressed_sensingv1/realdatasets/misc/starch-sanchez-v3/matrices/B6.pkl")
Bdf = pd.DataFrame(B)

tableg = table.T
species_ones = [] 
for i in range(6):
    species = i
    species_ones.append(list(tableg[tableg[species]==1].index))
    
    
species_zeros = []
for i in range(6):
    species = i
    species_zeros.append(list(tableg[tableg[species]==0].index))

In [2]:
sp_list_provided = ["C","E","M","P","S","T"]

n = 2**6
random_state = None
cv_splitsl = [3,5]

In [3]:
sstv3 = pd.read_pickle("starch-sanchez-relative.pkl")

In [4]:
wellsp = list(sstv3.index)

In [5]:
list_present = wellsp
dtr = []
dte = [] 
for cv_splits in cv_splitsl: 
    for speciesc in range(6):
        df2 = pd.DataFrame(species_ones[speciesc])
        idxlist = list(df2[0].values)
        abunvec = pd.DataFrame(sstv3[sp_list_provided[speciesc]][list(set(wellsp).intersection(species_ones[speciesc]))])
        pp = list(abunvec.index)
        redlist = []
        for kk in pp:
            redlist.append(idxlist.index(kk))
        abunvec.index = redlist
        data_present = list(abunvec.index)
        random.shuffle(data_present)
        data_present1 = np.array(data_present)
        kf = KFold(n_splits=cv_splits)
        kf.get_n_splits(data_present)
        count = 0 
        for train_index, test_index in kf.split(data_present1):
            X_train, X_test = data_present1[train_index], data_present1[test_index]
            rinew = list(X_train)
            rileft = list(X_test)
            y3 = abunvec.T[rinew].T[sp_list_provided[speciesc]].values  
            dtr.append([cv_splits,count,rinew,speciesc])
            dte.append([cv_splits,count,rileft,speciesc])
            count = count + 1

In [6]:
dtrf = pd.DataFrame(dtr,columns=["k-fold","fold number","train data","species"])

dtef = pd.DataFrame(dte,columns=["k-fold","fold number","test data","species"])

dtrf.to_pickle("traindataRELss.pkl")
dtef.to_pickle("testdataRELss.pkl")

In [7]:
abunvec

           T
0        1.0
1   0.962406
2   0.743191
3   0.044776
4   0.942857
5   0.060976
6   0.507463
7        0.0
8   0.851852
9   0.695652
10  0.722222
11  0.052356
12  0.955556
13  0.555556
14  0.267516
15       0.0
16  0.952381
18  0.645833
20  0.113924
22       0.0
23  0.002755
26  0.522936
27  0.010526
28  0.833333
29  0.459418
30   0.11879
31   0.01875